linters:
  flake8:
  
  rubocop:
  
  phpcs:
    standard: PSR2

  shellcheck:
    shell: bash
  csslint: {  }
  
  checkstyle:
    config: google_checks.xml
  
files:
  ignore:
    - 'vendor/*'
    - 'bower_components/*'
    - 'node_modules/*'
